image: mcr.microsoft.com/dotnet/sdk:latest
stages:
- build
- test
- release

build-release:
  stage: build
  script:
    - ./release.sh
  artifacts:
    paths:
      - '**/*.nupkg'
      - '**/*.snupkg'
  only:
    - master

build-prerelease:
  stage: build
  script:
    - ./release.sh "develop$CI_PIPELINE_ID"
  artifacts:
    paths:
      - '**/*.nupkg'
      - '**/*.snupkg'
  except:
    - master

unittest:
  stage: test
  script:
    - ./unittest.sh

publish:
  stage: release
  script:
    - ./publish.sh "$NUGET_GL_L4N"
  only:
    - master
    - develop
